/**
 * Position manager — reads and writes the companion `.view.sysml` file
 * that stores node layout positions for the threat model canvas.
 */

import * as path from 'path';
import * as vscode from 'vscode';
import type { NodePosition } from './types';

// ── Public API ───────────────────────────────────────────────────

export async function loadPositions(docUri: vscode.Uri): Promise<NodePosition[]> {
  const viewUri = getViewUri(docUri);
  try {
    const raw = Buffer.from(await vscode.workspace.fs.readFile(viewUri)).toString('utf-8');
    return parseViewFile(raw);
  } catch {
    return [];
  }
}

export async function savePosition(
  docUri: vscode.Uri, partName: string, x: number, y: number,
  width?: number, height?: number,
): Promise<void> {
  const positions = await loadPositions(docUri);
  const existing = positions.find(p => p.partName === partName);
  if (existing) {
    existing.x = Math.round(x);
    existing.y = Math.round(y);
    if (width !== undefined) { existing.width = Math.round(width); }
    if (height !== undefined) { existing.height = Math.round(height); }
  } else {
    positions.push({
      partName, x: Math.round(x), y: Math.round(y),
      ...(width !== undefined ? { width: Math.round(width) } : {}),
      ...(height !== undefined ? { height: Math.round(height) } : {}),
    });
  }
  await writeViewFile(docUri, positions);
}

export async function removePosition(docUri: vscode.Uri, partName: string): Promise<void> {
  const positions = await loadPositions(docUri);
  const filtered = positions.filter(p => p.partName !== partName);
  await writeViewFile(docUri, filtered);
}

export async function handleMove(
  docUri: vscode.Uri,
  msg: { partName: string; x: number; y: number; width?: number; height?: number },
): Promise<void> {
  await savePosition(docUri, msg.partName, msg.x, msg.y, msg.width, msg.height);
}

// ── Internal helpers ─────────────────────────────────────────────

function getViewUri(docUri: vscode.Uri): vscode.Uri {
  const dir = path.dirname(docUri.fsPath);
  const base = path.basename(docUri.fsPath, '.sysml');
  return vscode.Uri.file(path.join(dir, `${base}.view.sysml`));
}

function parseViewFile(text: string): NodePosition[] {
  const positions: NodePosition[] = [];
  const re = /@NodeLayout\s*\{\s*x\s*=\s*([\d.]+)\s*;\s*y\s*=\s*([\d.]+)\s*;(?:\s*w\s*=\s*([\d.]+)\s*;)?(?:\s*h\s*=\s*([\d.]+)\s*;)?\s*\}\s*\n\s*part\s+(\w+)\s*;/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(text)) !== null) {
    const pos: NodePosition = {
      partName: m[5],
      x: parseFloat(m[1]),
      y: parseFloat(m[2]),
    };
    if (m[3]) { pos.width = parseFloat(m[3]); }
    if (m[4]) { pos.height = parseFloat(m[4]); }
    positions.push(pos);
  }
  return positions;
}

async function writeViewFile(docUri: vscode.Uri, positions: NodePosition[]): Promise<void> {
  const viewUri = getViewUri(docUri);
  const baseName = path.basename(docUri.fsPath, '.sysml');
  const pkgName = baseName.replace(/[^a-zA-Z0-9]/g, '_');

  const lines: string[] = [
    `package ${pkgName}_View {`,
    `\tdoc /* Diagram layout for ${baseName}.sysml — auto-generated by Threat Model Editor. */`,
    ``,
    `\tmetadata def NodeLayout {`,
    `\t\tattribute x : ScalarValues::Real;`,
    `\t\tattribute y : ScalarValues::Real;`,
    `\t}`,
    ``,
    `\tpart diagramPositions {`,
  ];

  for (const pos of positions) {
    const dims = (pos.width || pos.height)
      ? ` w = ${pos.width ?? 400}; h = ${pos.height ?? 300};`
      : '';
    lines.push(`\t\t@NodeLayout { x = ${pos.x}; y = ${pos.y};${dims} }`);
    lines.push(`\t\tpart ${pos.partName};`);
    lines.push(``);
  }

  lines.push(`\t}`);
  lines.push(`}`);
  lines.push(``);

  await vscode.workspace.fs.writeFile(viewUri, Buffer.from(lines.join('\n'), 'utf-8'));
}
